addLayer("a", {
    name: "Spore Records",
    symbol: "★",
    startData() { return {
        unlocked: true,
        points: new Decimal(0),
    }},
    color: "#f3c53d",
    resource: "records",
    row: "side",
    tooltip() { return "Spore Records" },
    achievementPopups: true,

    update(diff) {
        if (hasAchievement("a", 21) && !hasMilestone("m", 0)) player.m.milestones.push(0)
        if (hasAchievement("a", 22) && !hasMilestone("e", 0)) player.e.milestones.push(0)
        if (hasAchievement("a", 31) && !hasUpgrade("h", 24)) player.h.upgrades.push(24)
        if (hasAchievement("a", 32) && !hasMilestone("f", 0)) player.f.milestones.push(0)
        if (hasAchievement("a", 41) && !hasUpgrade("r", 12)) player.r.upgrades.push(12)
    },

    achievements: {
        11: { name: "The spore wakes", done() { return player.points.gte(100) }, tooltip: "Have 100 Detritus.<br>Reward: Detritus gain ×1.5" },
        12: { name: "First filaments", done() { return player.h.best.gte(10) }, tooltip: "Have 10 hyphae.<br>Reward: Detritus gain ×1.5" },
        13: { name: "Shopping list", done() { return player.h.upgrades.length >= 5 }, tooltip: "Buy 5 Hyphae upgrades.<br>Reward: Detritus gain ×2" },
        14: { name: "Reaching out", done() { return player.h.best.gte(25) }, tooltip: "Have 25 hyphae.<br>Reward: Detritus gain ×2" },
        15: { name: "Specialization", done() { return player.m.best.gte(1) || player.e.best.gte(1) }, tooltip: "Prestige into Mycelium or Enzymes.<br>Reward: Detritus gain ×3" },
        21: { name: "A hundred strands", done() { return player.m.best.gte(100) }, tooltip: "Have 100 mycelium.<br>Reward: mycelium milestone 0, forever" },
        22: { name: "Chemical works", done() { return player.e.best.gte(100) }, tooltip: "Have 100 enzymes.<br>Reward: enzyme milestone 0, forever" },
        23: { name: "Ground floor", done() { return player.s.best.gte(5) }, tooltip: "Own 5 substrate layers.<br>Reward: Detritus gain ×5" },
        24: { name: "Brewing", done() { return player.y.best.gte(10) }, tooltip: "Have 10 yeast cultures.<br>Reward: Detritus gain ×5" },
        25: { name: "It fruits", done() { return player.f.best.gte(5) }, tooltip: "Have 5 fruiting bodies.<br>Reward: fruiting milestone 0, forever" },
        31: { name: "Deep horizons", done() { return player.h.best.gte(2500) }, tooltip: "Have 2,500 hyphae.<br>Reward: Hyphae upgrade 24, forever" },
        32: { name: "Orchard begun", done() { return player.f.best.gte(100) }, tooltip: "Have 100 fruiting bodies.<br>Reward: fruiting milestone 0, forever" },
        33: { name: "Trial by weather", done() { return hasChallenge("f", 11) || hasChallenge("f", 12) }, tooltip: "Complete any Fruiting challenge.<br>Reward: Detritus gain ×20" },
        34: { name: "Self-sustaining", done() { return player.h.best.gte(1e4) }, tooltip: "Have 10,000 hyphae.<br>Reward: hyphae grow on their own, forever" },
        35: { name: "A million deaths", done() { return player.points.gte(1e6) }, tooltip: "Have 1e6 Detritus.<br>Reward: Detritus gain ×50" },
        41: { name: "First contact", done() { return player.r.best.gte(5) }, tooltip: "Own 5 network reach.<br>Reward: Web upgrade 12, forever" },
        42: { name: "The floor runs itself", done() { return player.t.best.gte(1) }, tooltip: "Reach The Grove.<br>Reward: hyphae decompose automatically, forever" },
        43: { name: "Three partners", done() { return player.o.best.gte(10) && player.p.best.gte(10) && player.l.best.gte(10) }, tooltip: "Have 10 bonds with each partner.<br>Reward: Detritus gain ×100" },
        44: { name: "Trillions of deaths", done() { return player.points.gte(1e12) }, tooltip: "Have 1e12 Detritus.<br>Reward: Detritus gain ×100" },
        45: { name: "First thought", done() { return player.q.best.gte(2) }, tooltip: "Have 2 thoughts.<br>Reward: hyphae upgrades buy themselves, forever" },
        51: { name: "The forest hunts", done() { return player.n.best.gte(1) || player.c.best.gte(1) }, tooltip: "Reach Nematode Nooses or Cordyceps Dominion.<br>Reward: Detritus gain ×200" },
        52: { name: "A trillion trillion", done() { return player.points.gte(1e20) }, tooltip: "Have 1e20 Detritus.<br>Reward: Detritus gain ×200" },
        53: { name: "Farmer and medicine", done() { return player.pa.best.gte(10) && player.pd.best.gte(10) }, tooltip: "Have 10 tended gardens and antibiotic yield.<br>Reward: Detritus gain ×500" },
        54: { name: "A thinking forest", done() { return player.q.best.gte(100) }, tooltip: "Have 100 thoughts.<br>Reward: Detritus gain ×500" },
        55: { name: "Who domesticated whom", done() { return player.pa.best.gte(150) }, tooltip: "Have 150 tended gardens.<br>Reward: Detritus gain ×1000" },
        61: { name: "Ocean of detritus", done() { return player.points.gte(1e30) }, tooltip: "Have 1e30 Detritus.<br>Reward: Detritus gain ×1000" },
        62: { name: "The old grove", done() { return player.t.best.gte(100) }, tooltip: "Have 100 grove vitality.<br>Reward: Detritus gain ×1000" },
        63: { name: "Ten thousand worms", done() { return player.n.best.gte(50) }, tooltip: "Have 50 traps.<br>Reward: Detritus gain ×1000" },
        64: { name: "Weathered everything", done() { return maxedChallenge("f", 11) && maxedChallenge("f", 12) && maxedChallenge("b", 11) && maxedChallenge("b", 12) && maxedChallenge("c", 11) && maxedChallenge("c", 12) }, tooltip: "Complete all 6 challenges.<br>Reward: Detritus gain ×2000" },
        65: { name: "Detritus dega", done() { return player.points.gte(1e50) }, tooltip: "Have 1e50 Detritus.<br>Reward: Detritus gain ×2000" },
        71: { name: "A thousand thoughts", done() { return player.q.best.gte(1000) }, tooltip: "Have 1,000 thoughts.<br>Reward: Detritus gain ×2000" },
        72: { name: "Remembered", done() { return player.pr.best.gte(10) }, tooltip: "Have 10 ancient giants.<br>Reward: Detritus gain ×5000" },
        73: { name: "To the stars", done() { return player.x.best.gte(10) }, tooltip: "Have 10 star seeds.<br>Reward: Detritus gain ×5000" },
        74: { name: "A googol of the dead", done() { return player.points.gte(1e100) }, tooltip: "Have 1e100 Detritus.<br>Reward: Detritus gain ×5000" },
        75: { name: "Fifth wave", done() { return player.z.best.gte(5) }, tooltip: "Have 5 the fruiting.<br>Reward: Detritus gain ×5000" },
        81: { name: "Beyond naming", done() { return player.points.gte(1e150) }, tooltip: "Have 1e150 Detritus.<br>Reward: Detritus gain ×1e4" },
        82: { name: "Fossil record", done() { return player.pr.best.gte(50) }, tooltip: "Have 50 ancient giants.<br>Reward: Detritus gain ×1e4" },
        83: { name: "Seeded skies", done() { return player.x.best.gte(50) }, tooltip: "Have 50 star seeds.<br>Reward: Detritus gain ×1e4" },
        84: { name: "The dead of worlds", done() { return player.points.gte(1e200) }, tooltip: "Have 1e200 Detritus.<br>Reward: Detritus gain ×1e4" },
        85: { name: "Fifteenth wave", done() { return player.z.best.gte(15) }, tooltip: "Have 15 the fruiting.<br>Reward: Detritus gain ×1e4" },
        91: { name: "Detritus singularity", done() { return player.points.gte(1e300) }, tooltip: "Have 1e300 Detritus.<br>Reward: Detritus gain ×2e4" },
        92: { name: "A hundred thousand minds", done() { return player.q.best.gte(1e5) }, tooltip: "Have 1e5 thoughts.<br>Reward: Detritus gain ×2e4" },
        93: { name: "The dead of galaxies", done() { return player.points.gte(1e400) }, tooltip: "Have 1e400 Detritus.<br>Reward: Detritus gain ×2e4" },
        94: { name: "THE GREAT FRUITING", done() { return player.z.best.gte(25) }, tooltip: "Complete the endgame: 25 fruiting waves.<br>Reward: Detritus gain ×5e4" },
        95: { name: "Completionist", done() { return player.z.upgrades.length >= 10 }, tooltip: "Buy all 10 Great Fruiting upgrades.<br>Reward: Detritus gain ×5e4" },
        101: { name: "Beyond the story", done() { return player.points.gte(1e500) }, tooltip: "Have 1e500 Detritus — you kept going.<br>Reward: Detritus gain ×1e5" },
        102: { name: "Hyphal infinity", done() { return player.h.best.gte(1e10) }, tooltip: "Have 1e10 hyphae.<br>Reward: Detritus gain ×1e5" },
        103: { name: "The weave endless", done() { return player.m.best.gte(1e6) }, tooltip: "Have 1e6 mycelium.<br>Reward: Detritus gain ×1e5" },
        104: { name: "The dead of everything", done() { return player.points.gte(1e600) }, tooltip: "Have 1e600 Detritus.<br>Reward: Detritus gain ×1e5" },
        105: { name: "Hundred waves", done() { return player.z.best.gte(100) }, tooltip: "Have 100 the fruiting — a true cosmic fungus.<br>Reward: Detritus gain ×1e6" },
    },
})

addLayer("st", {
    name: "Field Notes",
    symbol: "S",
    startData() { return {
        unlocked: true,
        points: new Decimal(0),
    }},
    color: "#9a9a8a",
    resource: "notes",
    row: "side",
    tooltip() { return "Field Notes" },
    type: "none",
    tabFormat: [
        ["display-text", function() { return "Time in the forest: " + formatTime(player.timePlayed) }],
        "blank",
        ["display-text", function() { return "<b>Detritus:</b> " + format(player.points) }],
        ["display-text", function() { return "<b>Phase I — Decay</b><br>hyphae: " + format(player.h.points) + " (best " + format(player.h.best) + ")<br>mycelium: " + format(player.m.points) + "<br>enzymes: " + format(player.e.points) + "<br>substrate layers: " + formatWhole(player.s.points) + "<br>yeast cultures: " + format(player.y.points) }],
        ["display-text", function() { return "<b>Phase II — Fruiting</b><br>fruiting bodies: " + format(player.f.points) + "<br>climate balance: " + format(player.w.points) + "<br>gill area: " + format(player.g.points) + "<br>glow: " + format(player.b.points) + "<br>insect allies: " + format(player.i.points) }],
        ["display-text", function() { return "<b>Phase III — Symbiosis</b><br>network reach: " + formatWhole(player.r.points) + "<br>gut-passed spores: " + format(player.d.points) + "<br>oak: " + format(player.o.points) + " | pine: " + format(player.p.points) + " | lichen: " + format(player.l.points) + "<br>grove vitality: " + format(player.t.points) }],
        ["display-text", function() { return "<b>Phase IV — Dominion</b><br>traps: " + format(player.n.points) + "<br>hosts: " + format(player.c.points) + "<br>gardens: " + format(player.pa.points) + " | yield: " + format(player.pd.points) + "<br>thoughts: " + format(player.q.points) }],
        ["display-text", function() { return "<b>Phase V — Cosmos</b><br>ancient giants: " + format(player.pr.points) + "<br>star seeds: " + format(player.x.points) + "<br>the fruiting: " + format(player.z.points) }],
        "blank",
        ["display-text", function() { return "<i>Records: " + formatWhole(player.a.achievements.length) + "/50</i>" }],
    ],
})
